services:
  server:
    image: sorokchat-server
    container_name: sorokchat-server
    build:
      context: .
      dockerfile: SorokChatServer.Application/Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"

