spring.datasource.url=jdbc:postgresql://localhost:5432/sorokchat
spring.datasource.username=postgres
spring.datasource.password=sorokovsky17
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
secret.key=sorok_chat_secret